import pandas as pd
df = pd.read_csv("SampleSuperstore.csv", encoding='latin1')
print("First 5 rows:\n", df.head())
print("\nColumns:\n", df.columns)
total_sales = df['Sales'].sum()
total_profit = df['Profit'].sum()
total_quantity = df['Quantity'].sum()
profit_margin = (total_profit / total_sales) * 100
print("\n--- KPI RESULTS ---")
print("Total Sales:", total_sales)
print("Total Profit:", total_profit)
print("Total Quantity Sold:", total_quantity)
print("Profit Margin (%):", profit_margin)
category_sales = df.groupby('Category')['Sales'].sum()
print("\n--- Sales by Category ---")
print(category_sales)
segment_sales = df.groupby('Segment')['Sales'].sum()
print("\n--- Sales by Segment ---")
print(segment_sales)
region_profit = df.groupby('Region')['Profit'].sum()
print("\n--- Profit by Region ---")
print(region_profit)
sub_category_sales = df.groupby('Sub-Category')['Sales'].sum()
print("\n--- Sales by Sub-Category ---")
print(sub_category_sales)
top_products = df.sort_values(by='Sales', ascending=False).head(5)
print("\n--- Top 5 Sales Records ---")
print(top_products)
df.to_csv("cleaned_superstore.csv", index=False)

print("\nCleaned data saved as 'cleaned_superstore.csv'")